## Put comments here that give an overall description of what your
## functions do
# these two functions work together to calculate and cache the inverse of a matris.
# because calculation of an inverse is computationally expensive, unless the initial matrix changes,
# it makes sense to cache the calculated inverse and rather retrieve it.
# makeCacheMatrix() generates a list object containing a series of functions, which point to the matrix object.
# cacheSolve() gets passed a list of functions, generated by makeCacheMatrix().
# It uses these these functions to generate, cache and print the inverse matrix.

## Write a short comment describing this function
# makeCacheMatrix() is passed a square matrix object. 
# It generates a list object containing a series of functions, which point to the matrix object.
# 1. it clears the inverse function
# 2. Caches a new matrix and clears the inverse cache
# 3. assign the matrix data to a variable
# 4. Caches the inverse
# 5. retrieve inverse from cache
# 6. Generates teh returned list object with the functions

makeCacheMatrix <- function(x = matrix()) {
  # 1
  inv <- NULL
  
  # 2
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  
  # 3
  get <- function() x
  
  # 4
  setinv <- function(inverse) inv <<- inverse
  
  # 5
  getinv <- function() inv
  
  # 6
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}

## Write a short comment describing this function
# cacheSolve() gets passed a list of functions, generated by makeCacheMatrix, which in turn point to a matrix object
# It uses these these functions in the following order to
# 1. retrieve a cached inverse
# 2. If the cached inverse exists, returnit and exit the function
# 3. If the cached inverse doesn't exist, the matrix data is retrieved with get()
# 4. the inverse is calculated 
# 5. the inverse is cached
# 6. the inverse is returned
cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  
  # 1
  inv <- x$getinv()
  
  # 2
  if(!is.null(inv)) {
    message("getting cached inverse matrix")
    return(inv)
  }
  
  # 3
  data <- x$get()
  
  # 4
  inv <- solve(data, ...)
  
  # 5
  x$setinv(inv)
  
  # 6
  inv
}


https://github.com/philmassie/ProgrammingAssignment2
a3725fc720a7615a6c1912eb1b5a3e04af7035fd